# Exercício:

## 01 – Dados as operações abaixo, qual o resultado da operação lógica: 
p and q and r and s and t?
<br>
<br>Como os operadores lógicos podem ser usados para inverter o resultado?

<br>p = 2.0 + 3.0 / 5.0 == 10
<br>q = (p + 10.2) - 5.0 * 2.0 <= 2.9
<br>r = 10 <= p / q + 33.8 < 100
<br>s = 5 != p / (q + r)
<br>t = 33 == s * 2

In [ ]:
p = 2.0 + 3.0 / 5.0 == 10
q = (p + 10.2) - 5.0 * 2.0 <= 2.9
r = 10 <= p / q + 33.8 < 100
s = 5 != p / (q + r)
t = 33 == s * 2

print(p, q, r, s, t)

False True True True False

In [2]:
p and q and r and s and t

False

In [3]:
p and q or r and s or t

True

In [4]:
not (p and q and r and s and t)

True

In [5]:
p is not q is r

True

## 02 – Usando apenas o operador or, qual seria o resultado final das operações abaixo? Como deve ser usado o not para inverter o resultado?

<br>p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>s = ['a',1,True,'b',0,False] > ['a',True,1]
<br>t = ['a',1,True,'b',0,False] == 1
<br>u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [6]:
p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
s = ['a',1,True,'b',0,False] > ['a',True,1]
t = ['a',1,True,'b',0,False] == 1
u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

p or q or r or s or t or u

True

In [7]:
not (p or q or r or s or t or u)

False

## 03 – No exercício 3 da aula 8 foi importado um arquivo .csv para um objeto da classe DataFrame pandas. Importe aqui o mesmo objeto e arredonde e edite o index como realizado no exercício 3 da aula 8. Usando operadores responda, a segunda linha é igual a terceira ou a terceira linha é igual a quarta?

In [8]:
import pandas as pd

In [9]:
df = pd.read_csv('lista_7_df.csv', index_col= 'Unnamed: 0').round(3)
df

         Primeira   Segunda  Terceira    Quarta    Média
Linha 1     2.600     2.800    34.729     0.069   10.050
Linha 2     0.139     6.760     7.840  1206.074  305.203
Linha 3     0.005     0.019     2.600     2.800    1.356
Linha 4    34.729     0.069     0.139     6.760   10.424
Linha 5     7.840  1206.074     0.005     0.019  303.484
Média       9.062   243.144     9.062   243.144  126.103

In [10]:
ex_3 = (df.loc['Linha 2'] == df.loc['Linha 3']).all() or (df.loc['Linha 3'] == df.loc['Linha 4']).all()
ex_3

np.False_

## 04 – Usando operadores verifique se todos os valores contidos na primeira linha são maiores ou iguais a 10.

In [11]:
df.loc['Linha 1'].all() >= 10

np.False_

## 05 – Usando operadores verifique se todos os valores contidos na terceira coluna estão entre 0 inclusive e 40.

In [22]:
((df['Terceira'] >= 0) & (df['Terceira'] <= 40)).all()

np.True_

## 06 – Usando operadores verifique se algum dos valores contidos na última linha está acima de 10.

In [12]:
df.loc['Média'].any() > 10

np.False_

## 07 – Recupere a DataFrame contendo apenas valores que estejam acima de 5 e abaixo de 7.

In [21]:
df7 = df[((df > 5) & (df < 7))]
display(df7)

         Primeira  Segunda  Terceira  Quarta  Média
Linha 1       NaN      NaN       NaN     NaN    NaN
Linha 2       NaN     6.76       NaN     NaN    NaN
Linha 3       NaN      NaN       NaN     NaN    NaN
Linha 4       NaN      NaN       NaN    6.76    NaN
Linha 5       NaN      NaN       NaN     NaN    NaN
Média         NaN      NaN       NaN     NaN    NaN

## 08 – Recupere a DataFrame contendo apenas valores que estejam abaixo de 5 inclusive ou acima de 7.

In [20]:
df8 = df[((df > 5) | (df > 7))]
display(df8)

         Primeira   Segunda  Terceira    Quarta    Média
Linha 1       NaN       NaN    34.729       NaN   10.050
Linha 2       NaN     6.760     7.840  1206.074  305.203
Linha 3       NaN       NaN       NaN       NaN      NaN
Linha 4    34.729       NaN       NaN     6.760   10.424
Linha 5     7.840  1206.074       NaN       NaN  303.484
Média       9.062   243.144     9.062   243.144  126.103

## 09 – Converta as duas últimas colunas do objeto DataFrame para dois objetos da classe numpy array. Algum dos valores contidos no primeiro array estão entre 2 inclusive e 5 inclusive?

In [15]:
import numpy as np

In [24]:
df_array_quarta = df.loc[:, 'Quarta'].to_numpy()
df_array_quinta = df.iloc[:, -1].to_numpy()
print(df_array_quarta, df_array_quinta)

[6.900000e-02 1.206074e+03 2.800000e+00 6.760000e+00 1.900000e-02
 2.431440e+02] [ 10.05  305.203   1.356  10.424 303.484 126.103]

## 10 – Os valores contidos nos dois arrays são superiores à -1 e inferiores à 12?

In [31]:
teste_quarta = (df_array_quarta > -1) & (df_array_quarta < 12)
teste_quinta = (df_array_quinta > -1) & (df_array_quinta < 12)

In [33]:
resultado_final = teste_quarta.all() and teste_quinta.all()
print(resultado_final)

False