# Exercício:

## 01 – Usando o método np.random.normal(), gere valores de expressão gênica de um conjunto de 1.000 genes. Esse conjunto de ter valores up e downregulated.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [11]:
quantidade = 1000
up = 621
down = 379

up_array = np.random.normal(2, 1.5, up)
down_array = np.random.normal(-2, 1.5, down)

up_down = np.concat([up_array, down_array])
up_down.shape

(1000,)

## 02 – Usando o método np.random.randint(), gere valores para o número de genes diferencialmente expressos em um conjunto de 1.000 pacientes. Esse conjunto deve ter valores up e downregulated.

Instancie um objeto da classe DataFrame, com os dados gerados nos dois exercícios.

In [8]:
up_down_pacientes = np.random.randint(-10,15,1000)
up_down_pacientes.shape

(1000,)

In [7]:
pacientes = [f"paciente_{i}" for i in range(1, 1001)]

In [16]:
df = pd.DataFrame({
    'Expressão': up_down,
    'Diferencial': up_down_pacientes,
    'Pacientes': pacientes  
})
df

     Expressão  Diferencial      Pacientes
0     1.808237           -4     paciente_1
1     3.283317          -10     paciente_2
2     3.223224            5     paciente_3
3     3.696626            4     paciente_4
4     0.320542            6     paciente_5
..         ...          ...            ...
995   0.865173            3   paciente_996
996  -1.826059           -4   paciente_997
997  -3.184104            1   paciente_998
998  -2.782570            6   paciente_999
999  -0.992241            6  paciente_1000

[1000 rows x 3 columns]

## 03 – Categorize em grupos de 6 os dados contidos na DataFrame anterior, segundo critérios escolhidos por você. Explique os critérios.

R.: Para o tipo de dado criado sendo interpretado como se fosse um unico gene testado em 1000 pacientes a classificação possível que imaginei foi distinguir eles por clasificação da expressão

In [15]:
bins = [-np.inf, -4, -1, 0, 1, 4, np.inf]

labels = [
    'Muito downregulated',
    'Downregulated',
    'Levemente down',
    'Neutro',
    'Levemente up',
    'Muito upregulated'
]

df['Grupo'] = pd.cut(df['Expressão'], bins=bins, labels=labels)
df.head()

   Expressão  Genes Diferencial   Pacientes         Grupo
0   1.808237                 -4  paciente_1  Levemente up
1   3.283317                -10  paciente_2  Levemente up
2   3.223224                  5  paciente_3  Levemente up
3   3.696626                  4  paciente_4  Levemente up
4   0.320542                  6  paciente_5        Neutro

## 04 – Defina uma função em Python que receba uma pd.Series contendo uma variável quantitativa e retorne uma DataFrame contendo a tabela de frequência.

Obtenha a tabela de frequência das variáveis criadas nos exercícios 1 e 2.

## 05 – Gere os gráficos de barras e linhas para as frequências em cada umas das variáveis.

### Expressão

### Número

## 06 – Gere os histogramas para as variáveis obtidas nos exercícios 1 e 2.

## 07 – Gere um gráfico de dispersão para as variáveis obtidas nos exercícios 1 e 2.

## 08 – Gere o mesmo gráfico do exercício 06, porém, categorizado.

## 09 – Gere o mesmo gráfico do exercício 07, porém, categorizado.

## 10 – Indique o tipo da variável:

- Discreta
- Contínua
- Ordinal
- Nominal

| Variável | Valor |
| :--- | :---: |
| # de células positivas||
| % de células positivas||
| Faixa de pH||
| Valor de pH||
| mol/L||
| UFC||
| D.O.||
| Grupo Sanguíneo||
| Sorologia||