# Exercício:

## 01 – Obtenha os resultados e retorne o objeto e código em Python dos seguintes cálculos:
a) 2.0 + 3.0 / 5.0

b) (a + 10.2) - 5.0 * 2.0

c) a / b + 33.8

d) a / (b + c)

e) d * 2

In [14]:
a = 2.0 + 3.0 / 5.0
b = (a + 10.2) - 5.0 * 2.0
c = a / b + 33.8
d = a / (b + c)
e = d * 2

print(a)
print(b)
print(c)
print(d)
print(e)

2.6
2.799999999999999
34.72857142857143
0.0692805481537876
0.1385610963075752

In [15]:
lista_a = [1, 2, 3, 4, 5]
lista_b = [10, 20, 30, 40, 50]
lista_c = [10, 20, 50, 80, 120]

## 02 – Obtenha os resultados e retorne o código do objeto em Python dos seguintes cálculos:
a) [2.0, 3.0, 5.0] + [10, 20, 30]

b) lista_a * 2

c) lista_a + lista_b

d) lista_a / (lista_b * lista_c)

In [16]:
lista_a = [2.0, 3.0, 5.0] + [10, 20, 30]
print(lista_a)

[2.0, 3.0, 5.0, 10, 20, 30]

In [17]:
lista_b = lista_a * 2
print(lista_b)

[2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]

In [18]:
lista_c = lista_a + lista_b
print(lista_c)

[2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]

In [19]:
lista_d = lista_a / (lista_b * lista_c)
print(lista_d)

TypeError: can't multiply sequence by non-int of type 'list'

## 03 – Usando os objetos simples obtidos no exercício 01 (a, b, c, d, e), instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [20]:
lista_obj = [
    a,
    b,
    c,
    d,
    e,
]

lista_raiz = [
    a ** 2,
    b ** 2,
    c ** 2,
    d ** 2,
    e ** 2,
]

lista_uniao = lista_obj + lista_raiz
print(lista_uniao)

[2.6, 2.799999999999999, 34.72857142857143, 0.0692805481537876, 0.1385610963075752, 6.760000000000001, 7.839999999999994, 1206.0736734693876, 0.004799794352489283, 0.019199177409957132]

## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [21]:
import numpy as np
import pandas as pd

In [22]:
lista_of = lista_uniao * 2

lista_array = np.array(lista_of)
print(lista_array)

[2.60000000e+00 2.80000000e+00 3.47285714e+01 6.92805482e-02
 1.38561096e-01 6.76000000e+00 7.84000000e+00 1.20607367e+03
 4.79979435e-03 1.91991774e-02 2.60000000e+00 2.80000000e+00
 3.47285714e+01 6.92805482e-02 1.38561096e-01 6.76000000e+00
 7.84000000e+00 1.20607367e+03 4.79979435e-03 1.91991774e-02]

In [23]:
lista_array = lista_array.reshape(5, 4)
print(lista_array)

[[2.60000000e+00 2.80000000e+00 3.47285714e+01 6.92805482e-02]
 [1.38561096e-01 6.76000000e+00 7.84000000e+00 1.20607367e+03]
 [4.79979435e-03 1.91991774e-02 2.60000000e+00 2.80000000e+00]
 [3.47285714e+01 6.92805482e-02 1.38561096e-01 6.76000000e+00]
 [7.84000000e+00 1.20607367e+03 4.79979435e-03 1.91991774e-02]]

## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [ ]:
help(np.mean)

Help on _ArrayFunctionDispatcher in module numpy:

mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)
    Compute the arithmetic mean along the specified axis.

    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.

    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.

        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computing the mean.  For integer inputs, the default
        is `float64`; for floating point inputs, it is the same as the
        input dtype.
    out : ndarray, optional
        Alternate output array in which to place the result.  The default
        is ``None``; if provided, it must have the same shape as the
        expected output, but the type will be cast if necessary.
        See :ref:`ufuncs-output-type` for more details.
        See :ref:`ufuncs-output-type` for more details.

    keepdims : bool, optional
        If this is set to True, the axes which are reduced are left
        in the result as dimensions with size one. With this option,
        the result will broadcast correctly against the input array.

        If the default value is passed, then `keepdims` will not be
        passed through to the `mean` method of sub-classes of
        `ndarray`, however any non-default value will be.  If the
        sub-class' method does not implement `keepdims` any
        exceptions will be raised.

    where : array_like of bool, optional
        Elements to include in the mean. See `~numpy.ufunc.reduce` for details.

        .. versionadded:: 1.20.0

    Returns
    -------
    m : ndarray, see dtype parameter above
        If `out=None`, returns a new array containing the mean values,
        otherwise a reference to the output array is returned.

    See Also
    --------
    average : Weighted average
    std, var, nanmean, nanstd, nanvar

    Notes
    -----
    The arithmetic mean is the sum of the elements along the axis divided
    by the number of elements.

    Note that for floating-point input, the mean is computed using the
    same precision the input has.  Depending on the input data, this can
    cause the results to be inaccurate, especially for `float32` (see
    example below).  Specifying a higher-precision accumulator using the
    `dtype` keyword can alleviate this issue.

    By default, `float16` results are computed using `float32` intermediates
    for extra precision.

    Examples
    --------
    >>> import numpy as np
    >>> a = np.array([[1, 2], [3, 4]])
    >>> np.mean(a)
    2.5
    >>> np.mean(a, axis=0)
    array([2., 3.])
    >>> np.mean(a, axis=1)
    array([1.5, 3.5])

    In single precision, `mean` can be inaccurate:

    >>> a = np.zeros((2, 512*512), dtype=np.float32)
    >>> a[0, :] = 1.0
    >>> a[1, :] = 0.1
    >>> np.mean(a)
    np.float32(0.54999924)

    Computing the mean in float64 is more accurate:

    >>> np.mean(a, dtype=np.float64)
    0.55000000074505806 # may vary

    Computing the mean in timedelta64 is available:

    >>> b = np.array([1, 3], dtype="timedelta64[D]")
    >>> np.mean(b)
    np.timedelta64(2,'D')

    Specifying a where argument:

    >>> a = np.array([[5, 9, 13], [14, 10, 12], [11, 15, 19]])
    >>> np.mean(a)
    12.0
    >>> np.mean(a, where=[[True], [False], [False]])
    9.0

In [35]:
lista_array_np = np.mean(lista_array, axis= 0).tolist()
print(lista_array_np)

[9.062386463846298, 243.14443063899026, 9.062386463846298, 243.14443063899026]

## 06 – Insira as médias das colunas no final do array do exercício 4.

**Contexto:**
- No exercício 4, você criou um array numpy com 5 linhas e 4 colunas (totalizando 20 valores)
- No exercício 5, você calculou a média de cada uma das 4 colunas (resultando em uma lista com 4 valores)

**Tarefa:**
1. Use o atributo `shape` do array do exercício 4 para calcular o número total de elementos.
2. Insira a lista de médias (do exercício 5) no final de outro array criado
3. Recupere e exiba o array resultante


Obs.:  Atributos não usam () na chamada.

In [36]:
lista_array.shape

(5, 4)

In [38]:
lista_6 = np.append(lista_array, [lista_array_np], axis=0)
lista_6

array([[2.60000000e+00, 2.80000000e+00, 3.47285714e+01, 6.92805482e-02],
       [1.38561096e-01, 6.76000000e+00, 7.84000000e+00, 1.20607367e+03],
       [4.79979435e-03, 1.91991774e-02, 2.60000000e+00, 2.80000000e+00],
       [3.47285714e+01, 6.92805482e-02, 1.38561096e-01, 6.76000000e+00],
       [7.84000000e+00, 1.20607367e+03, 4.79979435e-03, 1.91991774e-02],
       [9.06238646e+00, 2.43144431e+02, 9.06238646e+00, 2.43144431e+02]])

## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [46]:
lista_7 = lista_6.reshape(-1,4)
lista_7

array([[2.60000000e+00, 2.80000000e+00, 3.47285714e+01, 6.92805482e-02],
       [1.38561096e-01, 6.76000000e+00, 7.84000000e+00, 1.20607367e+03],
       [4.79979435e-03, 1.91991774e-02, 2.60000000e+00, 2.80000000e+00],
       [3.47285714e+01, 6.92805482e-02, 1.38561096e-01, 6.76000000e+00],
       [7.84000000e+00, 1.20607367e+03, 4.79979435e-03, 1.91991774e-02],
       [9.06238646e+00, 2.43144431e+02, 9.06238646e+00, 2.43144431e+02]])

In [44]:
lista_7_df = pd.DataFrame(lista_7).round(3)
display(lista_7_df)

        0         1       2         3
0   2.600     2.800  34.729     0.069
1   0.139     6.760   7.840  1206.074
2   0.005     0.019   2.600     2.800
3  34.729     0.069   0.139     6.760
4   7.840  1206.074   0.005     0.019
5   9.062   243.144   9.062   243.144

## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [49]:
df_1 = lista_7_df.mean(axis= 1)
df_1

0     10.04950
1    305.20325
2      1.35600
3     10.42425
4    303.48450
5    126.10300
dtype: float64

In [54]:
lista_7_df ['medias'] = df_1
lista_7_df

        0         1       2         3     medias
0   2.600     2.800  34.729     0.069   10.04950
1   0.139     6.760   7.840  1206.074  305.20325
2   0.005     0.019   2.600     2.800    1.35600
3  34.729     0.069   0.139     6.760   10.42425
4   7.840  1206.074   0.005     0.019  303.48450
5   9.062   243.144   9.062   243.144  126.10300

## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [59]:
lista_7_df.describe()

               0            1          2            3      medias
count   6.000000     6.000000   6.000000     6.000000    6.000000
mean    9.062500   243.144333   9.062500   243.144333  126.103417
std    13.143019   481.471087  13.143019   481.471087  145.569845
min     0.005000     0.019000   0.005000     0.019000    1.356000
25%     0.754250     0.751750   0.754250     0.751750   10.143187
50%     5.220000     4.780000   5.220000     4.780000   68.263625
75%     8.756500   184.048000   8.756500   184.048000  259.139125
max    34.729000  1206.074000  34.729000  1206.074000  305.203250

In [61]:
lista_7_df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
0,6.0,9.062500,13.143019,0.005,0.754250,5.220000,8.756500,34.72900
1,6.0,243.144333,481.471087,0.019,0.751750,4.780000,184.048000,1206.07400
2,6.0,9.062500,13.143019,0.005,0.754250,5.220000,8.756500,34.72900
3,6.0,243.144333,481.471087,0.019,0.751750,4.780000,184.048000,1206.07400
medias,6.0,126.103417,145.569845,1.356,10.143187,68.263625,259.139125,305.20325

## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [68]:
lista_7_df

         Primeira   Segunda  Terceira    Quarta      Média
Linha 1     2.600     2.800    34.729     0.069   10.04950
Linha 2     0.139     6.760     7.840  1206.074  305.20325
Linha 3     0.005     0.019     2.600     2.800    1.35600
Linha 4    34.729     0.069     0.139     6.760   10.42425
Linha 5     7.840  1206.074     0.005     0.019  303.48450
Média       9.062   243.144     9.062   243.144  126.10300

In [69]:
lista_7_df.columns = ['Primeira', 'Segunda', 'Terceira', 'Quarta', 'Média',]
lista_7_df.index = ['Linha 1', 'Linha 2', 'Linha 3', 'Linha 4', 'Linha 5', 'Média',]
lista_7_df

         Primeira   Segunda  Terceira    Quarta      Média
Linha 1     2.600     2.800    34.729     0.069   10.04950
Linha 2     0.139     6.760     7.840  1206.074  305.20325
Linha 3     0.005     0.019     2.600     2.800    1.35600
Linha 4    34.729     0.069     0.139     6.760   10.42425
Linha 5     7.840  1206.074     0.005     0.019  303.48450
Média       9.062   243.144     9.062   243.144  126.10300

Média das médias é 126.10300