# Exercício:

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?
## R: Sim, uma matriz pode ser constituida de variaveis unidimensionais, como fazer uma lista de listas

In [6]:
frutas = ["maçã", "banana", "laranja", "uva"]
verduras = ["alface", "tomate", "cenoura", "espinafre"]
basico = ["arroz", "feijão", "macarrão", "pão"]

mercado =[
    frutas,
    verduras,
    basico,
]
print(mercado)

[['maçã', 'banana', 'laranja', 'uva'], ['alface', 'tomate', 'cenoura', 'espinafre'], ['arroz', 'feijão', 'macarrão', 'pão']]

## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [7]:
genes = ['BCRA1', 'TP53', 'HLA-A', 'SOD2', 'APOE']
gene_brca1 = [
    len(genes[0]),
    (genes[0][0:2]),
    genes[0].count("A"),
    "hu"in genes[0],
]
print(gene_brca1)

gene_tp53 = [
    len(genes[1]),
    (genes[1][0:2]),
    genes[1].count("A"),
    "hu"in genes[1],
]
print(gene_tp53)

gene_hla_a = [
    len(genes[2]),
    (genes[2][0:2]),
    genes[2].count("A"),
    "hu"in genes[2],
]
print(gene_hla_a)

gene_sod2 = [
    len(genes[3]),
    (genes[3][0:2]),
    genes[3].count("A"),
    "hu"in genes[3],
]
print(gene_sod2)

gene_apoe = [
    len(genes[4]),
    (genes[4][0:2]),
    genes[4].count("A"),
    "hu"in genes[4],
]

lista_genes = [
    gene_brca1,
    gene_tp53,
    gene_hla_a,
    gene_sod2,
    gene_apoe
]

[5, 'BC', 1, False]
[4, 'TP', 0, False]
[5, 'HL', 2, False]
[4, 'SO', 0, False]

In [8]:
print(lista_genes)

[[5, 'BC', 1, False], [4, 'TP', 0, False], [5, 'HL', 2, False], [4, 'SO', 0, False], [4, 'AP', 1, False]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [4]:
import numpy as np
import pandas as pd

In [9]:
genes_array = np.array(lista_genes)
print(genes_array)

[['5' 'BC' '1' 'False']
 ['4' 'TP' '0' 'False']
 ['5' 'HL' '2' 'False']
 ['4' 'SO' '0' 'False']
 ['4' 'AP' '1' 'False']]

## 4 – Recupere todos os itens do terceiro gene.

In [10]:
genes_array[2]

array(['5', 'HL', '2', 'False'], dtype='<U21')

## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

In [11]:
genes_array[:, 3]

array(['False', 'False', 'False', 'False', 'False'], dtype='<U21')

## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [12]:
display(genes_array[1, 1:3])
display(genes_array[3, 1:3])

array(['TP', '0'], dtype='<U21')

array(['SO', '0'], dtype='<U21')

## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [13]:
dicionario_genes = {
    genes[0]: gene_brca1,
    genes[1]: gene_tp53,
    genes[2]: gene_hla_a,
    genes[3]: gene_sod2,
    genes[4]: gene_apoe
}
print(dicionario_genes)

genes_df = pd.DataFrame(dicionario_genes)
genes_df_tp = genes_df.transpose()
display(genes_df_tp)

{'BCRA1': [5, 'BC', 1, False], 'TP53': [4, 'TP', 0, False], 'HLA-A': [5, 'HL', 2, False], 'SOD2': [4, 'SO', 0, False], 'APOE': [4, 'AP', 1, False]}

       0   1  2      3
BCRA1  5  BC  1  False
TP53   4  TP  0  False
HLA-A  5  HL  2  False
SOD2   4  SO  0  False
APOE   4  AP  1  False

In [14]:
genes_df_tp.rename(columns={
    0: "Tamanho", 
    1: "Início", 
    2: "Contagem de A", 
    3: "Contém hu?"}, 
    inplace=True
    )
display(genes_df_tp)

      Tamanho Início Contagem de A Contém hu?
BCRA1       5     BC             1      False
TP53        4     TP             0      False
HLA-A       5     HL             2      False
SOD2        4     SO             0      False
APOE        4     AP             1      False

## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [15]:
display(genes_df_tp[['Tamanho', 'Contagem de A']])

      Tamanho Contagem de A
BCRA1       5             1
TP53        4             0
HLA-A       5             2
SOD2        4             0
APOE        4             1

## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [16]:
display(genes_df_tp.iloc[[0, 2], 3])

BCRA1    False
HLA-A    False
Name: Contém hu?, dtype: object

## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.

In [3]:
import os

os.listdir()

['Atividade2.ipynb',
 '.DS_Store',
 'Atividade4.ipynb',
 'Atividade3.ipynb',
 'Atividade1.ipynb',
 'Atividade5.ipynb']

In [17]:
df_csv = pd.read_csv('../Pratica_de_Aula/data.csv')
display(df_csv)

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36629,404309,FL,PINELLAS COUNTY,0.0,88722.00,0.0,88722.0,88722.00,155065.65,0.0,0.0,0.0,0,28.122885,-82.770218,Residential,Wood,3
36630,465875,FL,PINELLAS COUNTY,1297057.5,1297057.50,1297057.5,1297057.5,1297057.50,1577500.79,0.0,0.0,0.0,0,28.080900,-82.758800,Residential,Masonry,1
36631,791209,FL,PINELLAS COUNTY,173286.9,173286.90,0.0,0.0,173286.90,205527.97,0.0,0.0,0.0,0,28.110550,-82.766360,Residential,Wood,4
36632,322627,FL,PINELLAS COUNTY,1499781.6,1499781.60,0.0,0.0,1499781.60,1768782.43,0.0,0.0,0.0,0,28.089415,-82.697411,Residential,Masonry,3
36633,398149,FL,PINELLAS COUNTY,373488.3,373488.30,0.0,0.0,373488.30,596003.67,0.0,0.0,0.0,0,28.064440,-82.774590,Residential,Masonry,1

In [18]:
entradas = len(df_csv)
tipos = list(df_csv.dtypes)
elementos = df_csv.dtypes.value_counts().tolist()

colunas = [df_csv.iloc[:,0], df_csv.iloc[:,3], df_csv.iloc[:,8]]
medias = [col.mean() for col in colunas]
desvios = [col.std() for col in colunas]
terceiro_quartil = [col.quantile(0.75) for col in colunas]

dic_csv = {
    'Num_entradas': entradas,
    'Medias': medias,
    'Desv_Pad': desvios,
    'Terc_Quartil': terceiro_quartil,
}

display(dic_csv)

{'Num_entradas': 36634,
 'Medias': [np.float64(548661.9371894961),
  np.float64(731478.0068460993),
  np.float64(2571004.0973420865)],
 'Desv_Pad': [np.float64(259912.9264939009),
  np.float64(17523003.588415086),
  np.float64(20367766.569178067)],
 'Terc_Quartil': [np.float64(774252.0),
  np.float64(0.0),
  np.float64(1128871.1824999999)]}