In [5]:
import pandas as pd
import numpy as np
import os

In [2]:
os.listdir()

['Aula_07_04.ipynb',
 'Aula_10_04_3.ipynb',
 'Aula_10_04.ipynb',
 'Aula_10_04_2.ipynb',
 'Aula_09_04_2.ipynb',
 'Aula_10_04_04.ipynb',
 'Aula_09_04.ipynb',
 'Aula_08_04.ipynb',
 'data_variable_edit.csv']

In [8]:
df = pd.read_csv("data_variable_edit.csv")
df.head()

     Sample  DV1 BR90  DV2 265  DV3 98  DV4 360         Cells  Treatment
0  Sample 1     44.54    39.56   81.42    48.23  CD4/CD8/CD19  Untreated
1  Sample 2     52.17    52.71   52.13    49.19  CD4/CD8/CD19  Untreated
2  Sample 3     45.37    52.28   42.48    50.88  CD4/CD8/CD19  Untreated
3  Sample 4     52.38    52.49   58.69    38.85  CD4/CD8/CD19  Untreated
4  Sample 5     49.51    51.85   51.10    47.40  CD4/CD8/CD19  Untreated

In [9]:
df.tail()

       Sample  DV1 BR90  DV2 265  DV3 98  DV4 360 Cells Treatment
175  Sample 2      0.45     0.45    0.45     0.45   CD8      Mock
176  Sample 3      0.58     0.58    0.58     0.58   CD8      Mock
177  Sample 4      0.76     0.76    0.76     0.76   CD8      Mock
178  Sample 5      0.60     0.60    0.60     0.60   CD8      Mock
179  Sample 6      0.65     0.65    0.65     0.65   CD8      Mock

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Sample     180 non-null    object
 1   DV1 BR90   180 non-null    float64
 2   DV2 265    180 non-null    float64
 3   DV3 98     180 non-null    float64
 4   DV4 360    180 non-null    float64
 5   Cells      180 non-null    object
 6   Treatment  180 non-null    object
dtypes: float64(4), object(3)
memory usage: 10.0+ KB

In [11]:
df.describe()

         DV1 BR90     DV2 265      DV3 98     DV4 360
count  180.000000  180.000000  180.000000  180.000000
mean     7.263833    7.413167    9.108333    6.624167
std     10.454712   10.944008   13.001236   10.534487
min      0.110000    0.110000    0.080000    0.010000
25%      1.387500    1.357500    1.067500    0.835000
50%      2.790000    2.595000    3.390000    1.970000
75%      6.900000    7.765000   12.047500    6.150000
max     52.380000   53.190000   81.420000   50.880000

In [18]:
df.select_dtypes(exclude= 'object').head()

   DV1 BR90  DV2 265  DV3 98  DV4 360
0     44.54    39.56   81.42    48.23
1     52.17    52.71   52.13    49.19
2     45.37    52.28   42.48    50.88
3     52.38    52.49   58.69    38.85
4     49.51    51.85   51.10    47.40

In [19]:
df.select_dtypes(exclude= 'number').describe()

          Sample         Cells  Treatment
count        180           180        180
unique         6             6          5
top     Sample 1  CD4/CD8/CD19  Untreated
freq          30            30         36

In [36]:
len.(df[df['Sample'] == 'Sample'])

SyntaxError: invalid syntax (400900956.py, line 1)

In [35]:
df.query('Cells == CD4/CD8/CD19')

UndefinedVariableError: name 'CD4' is not defined

In [34]:
df.query('Cells == 'CD4/CD8/CD19' and Sample == 'sample')')

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1122676910.py, line 1)

In [33]:
df.loc[:, ['Cells', 'Sample']]

            Cells    Sample
0    CD4/CD8/CD19  Sample 1
1    CD4/CD8/CD19  Sample 2
2    CD4/CD8/CD19  Sample 3
3    CD4/CD8/CD19  Sample 4
4    CD4/CD8/CD19  Sample 5
..            ...       ...
175           CD8  Sample 2
176           CD8  Sample 3
177           CD8  Sample 4
178           CD8  Sample 5
179           CD8  Sample 6

[180 rows x 2 columns]

In [25]:
df.loc[::-1].head

<bound method NDFrame.head of        Sample  DV1 BR90  DV2 265  DV3 98  DV4 360         Cells  Treatment
179  Sample 6      0.65     0.65    0.65     0.65           CD8       Mock
178  Sample 5      0.60     0.60    0.60     0.60           CD8       Mock
177  Sample 4      0.76     0.76    0.76     0.76           CD8       Mock
176  Sample 3      0.58     0.58    0.58     0.58           CD8       Mock
175  Sample 2      0.45     0.45    0.45     0.45           CD8       Mock
..        ...       ...      ...     ...      ...           ...        ...
4    Sample 5     49.51    51.85   51.10    47.40  CD4/CD8/CD19  Untreated
3    Sample 4     52.38    52.49   58.69    38.85  CD4/CD8/CD19  Untreated
2    Sample 3     45.37    52.28   42.48    50.88  CD4/CD8/CD19  Untreated
1    Sample 2     52.17    52.71   52.13    49.19  CD4/CD8/CD19  Untreated
0    Sample 1     44.54    39.56   81.42    48.23  CD4/CD8/CD19  Untreated

[180 rows x 7 columns]>

In [27]:
df[df.columns[1:5]].head(10)

   DV1 BR90  DV2 265  DV3 98  DV4 360
0     44.54    39.56   81.42    48.23
1     52.17    52.71   52.13    49.19
2     45.37    52.28   42.48    50.88
3     52.38    52.49   58.69    38.85
4     49.51    51.85   51.10    47.40
5     50.16    53.19   50.76    46.78
6     23.44    19.50   27.48    25.89
7     25.76    26.92   32.45    27.97
8     29.13    35.21   36.23    29.84
9     25.75    26.92   32.06    28.35

In [28]:
df[df[df.columns[-2]].isin(['CD4/CD8/CD19', 'CD4/CD8'])].head()

     Sample  DV1 BR90  DV2 265  DV3 98  DV4 360         Cells  Treatment
0  Sample 1     44.54    39.56   81.42    48.23  CD4/CD8/CD19  Untreated
1  Sample 2     52.17    52.71   52.13    49.19  CD4/CD8/CD19  Untreated
2  Sample 3     45.37    52.28   42.48    50.88  CD4/CD8/CD19  Untreated
3  Sample 4     52.38    52.49   58.69    38.85  CD4/CD8/CD19  Untreated
4  Sample 5     49.51    51.85   51.10    47.40  CD4/CD8/CD19  Untreated

In [ ]:
df[~df[df.columns[-2]].isin(['CD4/CD8/CD19', 'CD4/CD8'])].head() #Somente para o que não é CD4/CD8/CD19 ou CD4/CD8

      Sample  DV1 BR90  DV2 265  DV3 98  DV4 360 Cells  Treatment
12  Sample 1      4.23     4.10   17.12     6.18  CD14  Untreated
13  Sample 2      5.58     4.12   12.19     3.13  CD14  Untreated
14  Sample 3      3.31     2.68    7.70     2.59  CD14  Untreated
15  Sample 4      5.54     4.39   12.34     6.66  CD14  Untreated
16  Sample 5      4.67     3.82   10.74     4.64  CD14  Untreated

In [32]:
df.value_counts('Cells')

Cells
CD14            30
CD19            30
CD4             30
CD4/CD8         30
CD4/CD8/CD19    30
CD8             30
Name: count, dtype: int64

In [ ]:
df.sort_index(ascending=False).head() #organizar entradas de acordo com o index

       Sample  DV1 BR90  DV2 265  DV3 98  DV4 360 Cells Treatment
179  Sample 6      0.65     0.65    0.65     0.65   CD8      Mock
178  Sample 5      0.60     0.60    0.60     0.60   CD8      Mock
177  Sample 4      0.76     0.76    0.76     0.76   CD8      Mock
176  Sample 3      0.58     0.58    0.58     0.58   CD8      Mock
175  Sample 2      0.45     0.45    0.45     0.45   CD8      Mock

In [ ]:
#valores maximos e valores minimos
df[df.columns[1]].nlargest(5)

3    52.38
1    52.17
5    50.16
4    49.51
2    45.37
Name: DV1 BR90, dtype: float64

In [ ]:
#valores maximos e valores minimos MESMA COISA UE DE CIMA, MAS PUXANDO PELO NOME DA COLUNA
df['DV1 BR90'].nlargest(5)

3    52.38
1    52.17
5    50.16
4    49.51
2    45.37
Name: DV1 BR90, dtype: float64

In [ ]:
df[df.columns].nlargest(5, columns= df.columns[1]) #mesma coisa que df[df.columns[1]].nlargest(5) para puxar toda a cadeia de dados relacionados a cada index da amostra com maior valor de DV1 BR90

     Sample  DV1 BR90  DV2 265  DV3 98  DV4 360         Cells  Treatment
3  Sample 4     52.38    52.49   58.69    38.85  CD4/CD8/CD19  Untreated
1  Sample 2     52.17    52.71   52.13    49.19  CD4/CD8/CD19  Untreated
5  Sample 6     50.16    53.19   50.76    46.78  CD4/CD8/CD19  Untreated
4  Sample 5     49.51    51.85   51.10    47.40  CD4/CD8/CD19  Untreated
2  Sample 3     45.37    52.28   42.48    50.88  CD4/CD8/CD19  Untreated

In [42]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,170,171,172,173,174,175,176,177,178,179
Sample,Sample 1,Sample 2,Sample 3,Sample 4,Sample 5,Sample 6,Sample 1,Sample 2,Sample 3,Sample 4,...,Sample 3,Sample 4,Sample 5,Sample 6,Sample 1,Sample 2,Sample 3,Sample 4,Sample 5,Sample 6
DV1 BR90,44.54,52.17,45.37,52.38,49.51,50.16,23.44,25.76,29.13,25.75,...,0.88,0.6,0.53,0.67,1.26,0.45,0.58,0.76,0.6,0.65
DV2 265,39.56,52.71,52.28,52.49,51.85,53.19,19.5,26.92,35.21,26.92,...,0.88,0.6,0.53,0.67,1.26,0.45,0.58,0.76,0.6,0.65
DV3 98,81.42,52.13,42.48,58.69,51.1,50.76,27.48,32.45,36.23,32.06,...,0.88,0.6,0.53,0.67,1.26,0.45,0.58,0.76,0.6,0.65
DV4 360,48.23,49.19,50.88,38.85,47.4,46.78,25.89,27.97,29.84,28.35,...,0.88,0.6,0.53,0.67,1.26,0.45,0.58,0.76,0.6,0.65
Cells,CD4/CD8/CD19,CD4/CD8/CD19,CD4/CD8/CD19,CD4/CD8/CD19,CD4/CD8/CD19,CD4/CD8/CD19,CD4/CD8,CD4/CD8,CD4/CD8,CD4/CD8,...,CD4,CD4,CD4,CD4,CD8,CD8,CD8,CD8,CD8,CD8
Treatment,Untreated,Untreated,Untreated,Untreated,Untreated,Untreated,Untreated,Untreated,Untreated,Untreated,...,Mock,Mock,Mock,Mock,Mock,Mock,Mock,Mock,Mock,Mock

In [45]:
df['Treatment'].value_counts()

Treatment
Untreated    36
5 ug         36
10 ug        36
20 ug        36
Mock         36
Name: count, dtype: int64

In [ ]:
# funcao para transformar variaveis categoricas em variaveis numericas, ou seja, criar colunas para cada categoria e preencher com 0 ou 1 de acordo com a categoria presente em cada linha
pd.get_dummies(df['Treatment']).head()

   10 ug  20 ug   5 ug   Mock  Untreated
0  False  False  False  False       True
1  False  False  False  False       True
2  False  False  False  False       True
3  False  False  False  False       True
4  False  False  False  False       True

In [51]:
(
    df.value_counts()
    .to_frame()
    .head()
)

                                                          count
Sample   DV1 BR90 DV2 265 DV3 98 DV4 360 Cells Treatment
Sample 1 0.52     0.76    0.08   0.13    CD8   20 ug          1
         0.80     0.80    0.80   0.80    CD4   Mock           1
         0.92     0.89    1.49   1.34    CD14  Mock           1
         1.19     1.14    1.38   1.27    CD19  Mock           1
         1.23     0.48    0.17   0.03    CD4   10 ug          1

In [60]:
coluna_1 = df.columns[0]
coluna_2 = df.columns[-1]
print(coluna_1, coluna_2)
display(
    df.value_counts([
        coluna_1, 
        coluna_2
        ])
        .to_frame()
        .rename(columns={'count': 'Freq Abso Simples'})
        .sort_index()
)

Sample Treatment

                    Freq Abso Simples
Sample   Treatment
Sample 1 10 ug                      6
         20 ug                      6
         5 ug                       6
         Mock                       6
         Untreated                  6
Sample 2 10 ug                      6
         20 ug                      6
         5 ug                       6
         Mock                       6
         Untreated                  6
Sample 3 10 ug                      6
         20 ug                      6
         5 ug                       6
         Mock                       6
         Untreated                  6
Sample 4 10 ug                      6
         20 ug                      6
         5 ug                       6
         Mock                       6
         Untreated                  6
Sample 5 10 ug                      6
         20 ug                      6
         5 ug                       6
         Mock                       6
         Untreated                  6
Sample 6 10 ug                      6
         20 ug                      6
         5 ug                       6
         Mock                       6
         Untreated                  6